name: test
on:
  push:
    branches:
    - e2e-test-dev
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise will fail to push refs to dest repo
    - run: pip3 install docutils
    - run: python3 generate_installation_sctipt.py
    - run: ls
    - run: sudo bash run.sh
    - run: sudo bash setup5GNetwork.sh
    - run: sudo bash deployKPIMON.sh
