name: test
on:
  push:
    branches:
    - master
    - gitlab-cicd

jobs:
  build:
    runs-on: Ubuntu-20.04
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise will fail to push refs to dest repo
    - run: pip3 install docutils
    - run: git submodule update --init --recursive --remote
    - run: python3 generate_installation_script.py
    - run: ls RIC-Deployment
    - run: sudo swapoff -a
    - name: Install Kubernetes, Docker, and Helm
      run: | 
          cd RIC-Deployment/tools/k8s/bin
          ./gen-cloud-init.sh 
          sudo ./k8s-1node-cloud-init-k_1_16-h_2_17-d_cur.sh
          sudo kubectl get pods -A
          sudo kubectl create ns ricinfra
          sudo helm install stable/nfs-server-provisioner --namespace ricinfra --name nfs-release-1
          sudo kubectl patch storageclass nfs -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
          sudo apt install nfs-common
    - name: Build Modified E2 docker Image
      run: | 
          sudo docker run -d -p 5001:5000 --restart=always --name ric registry:2
          cd ../../../..
          cd ric-plt-e2
          ls

    #- run: sudo bash setup5GNetwork.sh
    #- run: sudo bash deployKPIMON.sh
