name: test
on:
  push:
    branches:
    - e2e-test-dev
    - master

jobs:
  build:
    runs-on: Ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise will fail to push refs to dest repo
    - run: pip3 install docutils
    - run: git submodule update --init --recursive --remote
    - run: python3 generate_installation_sctipt.py
    - run: ls RIC-Deployment
    - run: | 
          cd RIC-Deployment/tools/k8s/bin/asdasdasd
          ./gen-cloud-init.sh 
    - run: sudo bash setup5GNetwork.sh
    - run: sudo bash deployKPIMON.sh
